.catalog:
  name: "Sniper"
  version: "2.1(es)"
  description: "Prometheus Monitoring Solution"
  uuid: prometheus-2
  minimum_rancher_version: v1.5.5
  questions:
  - variable: "RANCHER_SERVER"
    label: "Rancher Server"
    description: "IP Address of the rancher server, no HTTP or slashes. This is only required for users that have enabled metrics to be exported by Rancher"
    default: "0.0.0.0"
    required: false
    type: "string"
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server"
    label: "VOLUME Driver"
    required: true
    default: "local"
    type: enum
    options:
      - local
      - rancher-nfs
      - rancher-efs
      - rancher-ebs
  - variable: "RANCHER_ENV"
    label: "Rancher env"
    description: "Rancher environment name"
    default: "manager"
    required: false
    type: "string"
  - variable: "URL"
    description: "Prometheus url"
    label: "url"
    required: true
    default: "https://prometheus-hz.sensetime.com"
    type: enum
    options:
      - https://prometheus-hz.sensetime.com
      - https://chaos.sensetime.com
  - variable: "BASIC_PATH"
    label: "basic path"
    description: "prometheus basic path"
    default: "manager"
    required: false
    type: "string"
  - variable: "ES_EXIST"
    description: "for elasticsearch monitoring"
    label: "es exist"
    required: true
    default: "false"
    type: enum
    options:
      - "false"
      - "true"
  - variable: "ES_NODE_COUNT"
    label: "es node count"
    description: "elasticsearch node total count"
    default: 0
    required: false
    type: "int"

  - variable: "ES_SOURCE"
    label: "es source"
    description: "elasticsearch source"
    default: none
    required: false
    type: "service"

  - variable: "PROMETHEUS_YAML"
    type: "multiline"
    label: "prometheus.yaml"
    description: |
      prometheus config yaml
    default: |
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
        external_labels:
            monitor: 'exporter-metrics'
      
      alerting:
        alertmanagers:
        - scheme: https
          static_configs:
          - targets:
            - alertmanager.sensetime.com
          basic_auth:
            username: alertmanager
            password: sensetime-alertmanager
      
      rule_files:
        - "container.yml" 
        - "host.yml"
        - "rancher.yml"
      
      scrape_configs:
      
      - job_name: 'HostsMetrics'
        dns_sd_configs:
        - names:
          - node-exporter
          refresh_interval: 15s
          type: A
          port: 9100
      
      - job_name: 'ContainerMetrics'
        dns_sd_configs:
        - names:
          - cadvisor
          refresh_interval: 15s
          type: A
          port: 8484
      
      - job_name: 'RancherApi'
        dns_sd_configs:
        - names:
          - 'prometheus-rancher-exporter'
          refresh_interval: 15s
          type: A
          port: 9173
      
      - job_name: 'Prometheus'
        metrics_path: /metrics
        static_configs:
          - targets:
            - '127.0.0.1:9090'
      
        #- job_name: NetworkConnectivity
        #  metrics_path: /probe
        #  params:
        #    name: [ping]
        #  dns_sd_configs:
        #  - names:
        #    - 'script-exporter'
        #    refresh_interval: 15s
        #    type: A
        #    port: 9172
        #
      - job_name: 'Elasticsearch'
        dns_sd_configs:
        - names:
          - 'es-exporter'
          refresh_interval: 15s
          type: A
          port: 9108
      
      - job_name: 'blackbox-exporter'
        metrics_path: /probe
        params:
          module: [http_2xx]  # look for a http 200 response.
        file_sd_configs:
          - files:
            - /etc/prom-conf/url.yml
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
       


prometheus:
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000


prometheus-rancher-exporter:
  scale: 1
  health_check:
    port: 9173
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

