.catalog:
  name: "Sniper"
  version: "1.0.0"
  description: "Prometheus Monitoring Solution"
  uuid: prometheus-2
  minimum_rancher_version: v1.5.5
  questions:
  - variable: "RANCHER_SERVER"
    label: "Rancher Server"
    description: "IP Address of the rancher server, no HTTP or slashes. This is only required for users that have enabled metrics to be exported by Rancher"
    default: "0.0.0.0"
    required: false
    type: "string"
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server"
    label: "VOLUME Driver"
    required: true
    default: "local"
    type: enum
    options:
      - local
      - rancher-nfs
      - rancher-efs
      - rancher-ebs
  - variable: "RANCHER_ENV"
    label: "Rancher env"
    description: "Rancher environment name"
    default: "manager"
    required: false
    type: "string"
  - variable: "URL"
    description: "Prometheus url"
    label: "url"
    required: true
    default: "https://prometheus-hz.sensetime.com"
    type: enum
    options:
      - https://prometheus-hz.sensetime.com
      - https://chaos.sensetime.com
  - variable: "BASIC_PATH"
    label: "basic path"
    description: "prometheus basic path"
    default: "manager"
    required: false
    type: "string"
  - variable: "ES_EXIST"
    description: "es-exporter"
    label: "es-exporter"
    required: true
    default: "false"
    type: enum
    options:
      - "false"
      - "true"

prometheus:
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000


prometheus-rancher-exporter:
  scale: 1
  health_check:
    port: 9173
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

