name: Sniper
description: >
   Sniper Stack for SenseTime Container Platform.
version: 1.0.0
category: Monitoring
maintainer: Areslan <xuejipeng@sensetime.com>
projectURL: https://github.com/xuejipeng/rancher-catalog

