groups:
- name: mongodb
  rules:
  - alert: mongodb_low_uptime
    expr: mongodb_instance_uptime_seconds < 20
    labels:
      severity: critical
    annotations:
      description: MongoDB uptime less than 20 seconds
  - alert: mongodb_replset_member_health
    expr: mongodb_replset_member_health{state!="(not reachable/healthy)"} < 1
    labels:
      severity: critical
    annotations:
      description: MongoDB ReplicaSet has at least one unhealthy member
  - alert: mongodb_has_no_primary_node
    expr: sum by(job) (mongodb_replset_member_state{state="PRIMARY"}) < 1
    labels:
      severity: critical
    annotations:
      description: MongoDB ReplicaSet has no primary node available
