cadvisor:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: google/cadvisor:latest
  command: --port=8484
  stdin_open: true
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  net: host

node-exporter:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: prom/node-exporter:latest
  stdin_open: true
  net: host

#script-exporter:
#  labels:
#    io.rancher.scheduler.global: 'true'
#  tty: true
#  image: registry.sensetime.com/sre/script-exporter:0b25031
#  stdin_open: true

es-exporter:
  tty: true
  image: justwatch/elasticsearch_exporter:1.0.1
  stdin_open: true
  command: -es.uri=http://elasticsearch:9200
  external_links:
  - ${ES_SOURCE}:elasticsearch

redis-exporter:
  tty: true
  image: oliver006/redis_exporter
  stdin_open: true
  external_links:
  - ${REDIS_SOURCE}:redis
  environment:
  - REDIS_ADDR=redis://:${REDIS_PASS}@redis.rancher.internal

prom-conf:
    tty: true
    image: registry.sensetime.com/sre/prom-conf:2.1.1
    volumes:
      - /etc/prom-conf/
    net: none
    environment:
      - RANCHER_ENV=${RANCHER_ENV}
      - BASIC_PATH=${BASIC_PATH}
      - ES_EXIST=${ES_EXIST}
      - ES_NODE_COUNT=${ES_NODE_COUNT}
      - REDIS_EXIST=${REDIS_EXIST}

prometheus:
    tty: true
    image: prom/prometheus:v2.2.0
    command: --config.file=/etc/prom-conf/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.route-prefix=${BASIC_PATH} --web.external-url=${URL}${BASIC_PATH}
    labels:
      io.rancher.sidekicks: prom-conf
    volumes_from:
      - prom-conf
    volumes:
      - prometheus-data:/prometheus
    volume_driver: ${VOLUME_DRIVER}
    links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    extra_hosts:
    - "rancher-server:${RANCHER_SERVER}"

prometheus-rancher-exporter:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    image: infinityworks/prometheus-rancher-exporter:v0.22.52

