groups:
- name: elasticsearch
  rules:
  - alert: elasticsearch_too_few_nodes_running
    annotations:
      description: There are only {{$value}} ElasticSearch nodes running
      summary: ElasticSearch running on less than 0
    expr: elasticsearch_cluster_health_number_of_nodes < 0
    for: 5m
    labels:
      severity: warning
  - alert: elasticsearch_heap_too_high
    annotations:
      description: The heap usage is over 90% for 15m
      summary: ElasticSearch node {{$labels.node}} heap usage is high
    expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}
      > 0.9
    for: 15m
    labels:
      severity: warning
  - alert: elasticsearch_bad_status
    annotations:
      DESCRIPTION: '{{$labels.instance}}: Elasticsearch cluster status is not green
        (or 0), current value is: {{ $value }}'
      SUMMARY: '{{$labels.instance}}: Elasticsearch cluster status is not green'
    expr: absent(elasticsearch_cluster_health_status) or (elasticsearch_cluster_health_status{color="red"})
      == 1
    for: 5m
    labels:
      severity: warning
