groups:
- name: host
  rules:
  - alert: node_load_high
    expr: node_load5 / count(count(node_cpu) WITHOUT (mode)) WITHOUT (cpu) > 1.2
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg load 5m is at {{ $value }}. Reported by instance {{ $labels.instance
        }} of job {{ $labels.job }}.
  - alert: node_cpu_iowait_high
    expr: avg(rate(node_cpu{mode="iowait"}[5m])) BY (instance) * 100 > 60
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg iowait time in 5m is {{ $value }}. Reported by instance
        {{ $labels.instance }} of job {{ $labels.job }}.
  - alert: node_memory_usage_high
    expr: (((node_memory_MemTotal - node_memory_MemFree - node_memory_Cached) / (node_memory_MemTotal))
      * 100) > 90 and (node_memory_MemFree + node_memory_Cached) < 2 * 1024 * 1024
      * 1024
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg memory usage in 5m is {{ $value }}%. Reported by instance
        {{ $labels.instance }} of job {{ $labels.job }}.
  - alert: node_network_traffic_high
    expr: rate(node_network_receive_bytes{device!~"docker0|veth.+"}[5m]) + rate(node_network_transmit_bytes{device!~"docker0|veth.+"}[5m])
      > 60 * 1024 * 1024
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg network traffic in 5m is {{ $value }}. Reported by instance
        {{ $labels.instance }} of job {{ $labels.job }}.
  - alert: node_network_errors
    expr: rate(node_network_receive_errs{device!~"(docker.+|veth.+|lo)"}[5m]) + rate(node_network_transmit_errs[5m])
      > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg network packet errors in 5m is {{ $value }}. Reported
        by instance {{ $labels.instance }} of job {{ $labels.job }}.
  - alert: node_disk_throughput_high
    expr: rate(node_disk_bytes_read[5m]) + rate(node_disk_bytes_written[5m]) > 100
      * 1024 * 1024
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg disk throughput in 5m is {{ $value }}. Reported by instance
        {{ $labels.instance }} of job {{ $labels.job }}.
  - alert: node_disk_space_running_out
    expr: (node_filesystem_avail / node_filesystem_size{fstype="aufs",mountpoint="/"}
      * 100) < 15
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Host avg disk space will be full in 2 days. Reported by instance
        {{ $labels.instance }} of job {{ $labels.job }}.
