alerting:
  alertmanagers:
  - basic_auth:
      password: sensetime-alertmanager
      username: alertmanager
    scheme: https
    static_configs:
    - targets:
      - alertmanager.sensetime.com
global:
  evaluation_interval: 15s
  external_labels:
    env: rancherenv
  scrape_interval: 15s
rule_files:
- container.yml
- host.yml
- rancher.yml
scrape_configs:
- dns_sd_configs:
  - names:
    - node-exporter
    port: 9100
    refresh_interval: 15s
    type: A
  job_name: HostsMetrics
- dns_sd_configs:
  - names:
    - cadvisor
    port: 8484
    refresh_interval: 15s
    type: A
  job_name: ContainerMetrics
- dns_sd_configs:
  - names:
    - prometheus-rancher-exporter
    port: 9173
    refresh_interval: 15s
    type: A
  job_name: RancherApi
- job_name: Prometheus
  metrics_path: /prometheus/metrics
  static_configs:
  - targets:
    - 127.0.0.1:9090
- dns_sd_configs:
  - names:
    - es-exporter
    port: 9108
    refresh_interval: 15s
    type: A
  job_name: Elasticsearch
- dns_sd_configs:
  - names:
    - mysql-exporter
    port: 9104
    refresh_interval: 15s
    type: A
  job_name: Mysql
- dns_sd_configs:
  - names:
    - mongodb-exporter
    port: 9001
    refresh_interval: 15s
    type: A
  job_name: MongoDB
- dns_sd_configs:
  - names:
    - redis-exporter
    port: 9121
    refresh_interval: 15s
    type: A
  job_name: Redis
- file_sd_configs:
  - files:
    - /etc/prom-conf/url.yml
  job_name: blackbox-exporter-http
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: blackbox-exporter:9115
    target_label: __address__
- file_sd_configs:
  - files:
    - /etc/prom-conf/tcp.yml
  job_name: blackbox-exporter-tcp
  metrics_path: /probe
  params:
    module:
    - tcp_connect
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: blackbox-exporter:9115
    target_label: __address__
