.catalog:
  name: "Sniper"
  version: "2.1(user-defined)"
  description: "Prometheus Monitoring Solution"
  uuid: prometheus-2
  minimum_rancher_version: v1.5.5
  questions:
  - variable: "RANCHER_SERVER"
    label: "Rancher Server"
    description: "IP Address of the rancher server, no HTTP or slashes. This is only required for users that have enabled metrics to be exported by Rancher"
    default: "0.0.0.0"
    required: false
    type: "string"
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server"
    label: "VOLUME Driver"
    required: true
    default: "local"
    type: enum
    options:
      - local
      - rancher-nfs
      - rancher-efs
      - rancher-ebs
  - variable: "RANCHER_ENV"
    label: "Rancher env"
    description: "Rancher environment name"
    default: "manager"
    required: false
    type: "string"
  - variable: "URL"
    description: "Prometheus url"
    label: "url"
    required: true
    default: "https://prometheus-hz.sensetime.com"
    type: enum
    options:
      - https://prometheus-hz.sensetime.com
      - https://chaos.sensetime.com
  - variable: "BASIC_PATH"
    label: "basic path"
    description: "prometheus basic path"
    default: "manager"
    required: false
    type: "string"
  - variable: "ES_EXIST"
    description: "for elasticsearch monitoring"
    label: "es exist"
    required: true
    default: "false"
    type: enum
    options:
      - "false"
      - "true"
  - variable: "ES_NODE_COUNT"
    label: "es node count"
    description: "elasticsearch node total count"
    default: 0
    required: false
    type: "int"

  - variable: "ES_SOURCE"
    label: "es source"
    description: "elasticsearch source"
    default: none
    required: false
    type: "service"

  - variable: "REDIS_SOURCE"
    label: "redis source"
    description: "redis source"
    default: none
    required: false
    type: "service"

  - variable: "REDIS_EXIST"
    description: "for redis monitoring"
    label: "redis exist"
    required: true
    default: "false"
    type: enum
    options:
      - "false"
      - "true"

  - variable: "REDIS_PASS"
    label: "redis password"
    description: "redis password"
    default: ""
    required: false
    type: "string"

  - variable: "MYSQL_EXIST"
    description: "for mysql monitoring"
    label: "mysql exist"
    required: true
    default: "false"
    type: enum
    options:
      - "false"
      - "true"

  - variable: "MYSQL_SOURCE"
    label: "mysql source"
    description: "mysql source"
    default: none
    required: false
    type: "service"

  - variable: "MYSQL_USER"
    label: "mysql_user"
    description: "mysql user"
    default: ""
    required: false
    type: "string"

  - variable: "MYSQL_PASS"
    label: "mysql_password"
    description: "mysql user password"
    default: ""
    required: false
    type: "string"


  - variable: "MONGODB_EXIST"
    description: "for mongodb monitoring"
    label: "mongodb exist"
    required: true
    default: "false"
    type: enum
    options:
      - "false"
      - "true"

  - variable: "MONGODB_MASTER_SOURCE"
    label: "mongodb-master"
    description: "mongodb master source"
    default: none
    required: false
    type: "service"

  - variable: "MONGODB_SLAVE_SOURCE"
    label: "mongodb-slave"
    description: "mongodb slave source"
    default: none
    required: false
    type: "service"

  - variable: "MONGODB_USER"
    label: "mongodb_user"
    description: "mongodb user"
    default: ""
    required: false
    type: "string"

  - variable: "MONGODB_PASS"
    label: "mongodb_password"
    description: "mongodb user password"
    default: ""
    required: false
    type: "string"

  - variable: "prometheus_yaml"
    label: "prom yaml"
    description: "prometheus config of prometheus"
    required: true
    type: "multiline"
    default: |
      alerting:
        alertmanagers:
        - basic_auth:
            password: sensetime-alertmanager
            username: alertmanager
          scheme: https
          static_configs:
          - targets:
            - alertmanager.sensetime.com
      global:
        evaluation_interval: 15s
        external_labels:
          env: rancherenv
        scrape_interval: 15s
      rule_files:
      - container.yml
      - host.yml
      - rancher.yml
      scrape_configs:
      - dns_sd_configs:
        - names:
          - node-exporter
          port: 9100
          refresh_interval: 15s
          type: A
        job_name: HostsMetrics
      - dns_sd_configs:
        - names:
          - cadvisor
          port: 8484
          refresh_interval: 15s
          type: A
        job_name: ContainerMetrics
      - dns_sd_configs:
        - names:
          - prometheus-rancher-exporter
          port: 9173
          refresh_interval: 15s
          type: A
        job_name: RancherApi
      - job_name: Prometheus
        metrics_path: /prometheus/metrics
        static_configs:
        - targets:
          - 127.0.0.1:9090
      - dns_sd_configs:
        - names:
          - es-exporter
          port: 9108
          refresh_interval: 15s
          type: A
        job_name: Elasticsearch
      - dns_sd_configs:
        - names:
          - mysql-exporter
          port: 9104
          refresh_interval: 15s
          type: A
        job_name: Mysql
      - dns_sd_configs:
        - names:
          - mongodb-exporter
          port: 9001
          refresh_interval: 15s
          type: A
        job_name: MongoDB
      - dns_sd_configs:
        - names:
          - redis-exporter
          port: 9121
          refresh_interval: 15s
          type: A
        job_name: Redis
      - file_sd_configs:
        - files:
          - /etc/prom-conf/url.yml
        job_name: blackbox-exporter-http
        metrics_path: /probe
        params:
          module:
          - http_2xx
        relabel_configs:
        - source_labels:
          - __address__
          target_label: __param_target
        - source_labels:
          - __param_target
          target_label: instance
        - replacement: blackbox-exporter:9115
          target_label: __address__
      - file_sd_configs:
        - files:
          - /etc/prom-conf/tcp.yml
        job_name: blackbox-exporter-tcp
        metrics_path: /probe
        params:
          module:
          - tcp_connect
        relabel_configs:
        - source_labels:
          - __address__
          target_label: __param_target
        - source_labels:
          - __param_target
          target_label: instance
        - replacement: blackbox-exporter:9115
          target_label: __address__


  - variable: "hosts_yaml"
    label: "prom hosts yaml"
    description: "prometheus alert rules of hosts"
    required: true
    type: "multiline"
    default: |
            groups:
            

  - variable: "app_yaml"
    label: "prom app yaml"
    description: "prometheus alert rules of app"
    required: false
    type: "multiline"
    default: |
        - targets: null

prometheus:
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
  metadata:
    app: |
         ${app_yaml}
    prometheus: |
         ${prometheus_yaml}
    hosts: |
         ${hosts_yaml}

prometheus-rancher-exporter:
  scale: 1
  health_check:
    port: 9173
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

